### ISSUE TITLE
How to use multigpu？

### ISSUE THREAD

**Issue by QX-N** [happyharrycn/actionformer_release#38]
I change the config file like this ，"devices": [0,1,2,3]  and  add code 
USE_CUDA = torch.cuda.is_available()
 device = torch.device("cuda:0" if USE_CUDA else "cpu")
but I got the error：
Traceback (most recent call last):
  File "/data1/qianxiong/Actionformer/train.py", line 186, in <module>
    main(args)
  File "/data1/qianxiong/Actionformer/train.py", line 128, in main
    train_one_epoch(
  File "/data1/qianxiong/Actionformer/libs/utils/train_utils.py", line 277, in train_one_epoch
    losses = model(video_list)
  File "/data1/qianxiong/anaconda3/envs/Actionformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/qianxiong/anaconda3/envs/Actionformer/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/data1/qianxiong/anaconda3/envs/Actionformer/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/data1/qianxiong/anaconda3/envs/Actionformer/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/data1/qianxiong/anaconda3/envs/Actionformer/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
IndexError: Caught IndexError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/data1/qianxiong/anaconda3/envs/Actionformer/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/data1/qianxiong/anaconda3/envs/Actionformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/qianxiong/Actionformer/libs/modeling/meta_archs.py", line 334, in forward
    batched_inputs, batched_masks = self.preprocessing(video_list)
  File "/data1/qianxiong/anaconda3/envs/Actionformer/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data1/qianxiong/Actionformer/libs/modeling/meta_archs.py", line 423, in preprocessing
    batched_inputs = batched_inputs.to(self.device)
  File "/data1/qianxiong/Actionformer/libs/modeling/meta_archs.py", line 330, in device
    return list(set(p.device for p in self.parameters()))[0]
IndexError: list index out of range

Process finished with exit code 1
Please tell me how to use multigpu to train your code？

**Comment by tzzcl** [comment]
Hi, our code currently does not support multi-GPU training.

Using a larger batch (along with multi-gpu training) may decrease the performance here.

**Comment by tzzcl** [comment]
By the way, if you really want to try on multi-gpu training, you may need to try use DistributedDataparallel model along with some distributed launch tweaks.

**Comment by QX-N** [comment]
OK ， I  get it
